drop table if exists base.usuario_permissao CASCADE;
drop table if exists base.ordem_servico_servico CASCADE;
drop table if exists base.ordem_servico_produto CASCADE;
drop table if exists base.ordem_servico CASCADE;
drop table if exists base.servico CASCADE;
drop table if exists base.produto CASCADE;
drop table if exists base.endereco CASCADE;
drop table if exists base.usuario CASCADE;
drop table if exists base.permissao CASCADE;
drop table if exists base.cliente CASCADE;
drop table if exists base.flyway_schema_history;