drop table if exists os_user_role CASCADE;
drop table if exists os_order_work CASCADE;
drop table if exists os_order_product CASCADE;
drop table if exists os_order CASCADE;
drop table if exists os_work CASCADE;
drop table if exists os_product CASCADE;
drop table if exists os_address CASCADE;
drop table if exists os_users CASCADE;
drop table if exists os_role CASCADE;
drop table if exists os_client CASCADE;
drop table if exists flyway_schema_history;