drop table if exists base.os_user_role CASCADE;
drop table if exists base.os_order_work CASCADE;
drop table if exists base.os_order_product CASCADE;
drop table if exists base.os_order CASCADE;
drop table if exists base.os_work CASCADE;
drop table if exists base.os_product CASCADE;
drop table if exists base.os_address CASCADE;
drop table if exists base.os_user CASCADE;
drop table if exists base.os_role CASCADE;
drop table if exists base.os_client CASCADE;
drop table if exists flyway_schema_history;